### ISSUE TITLE
Invalidate if it is a variable

### ISSUE THREAD

**Issue by joker77877** [bluwy/svelte-preprocess-import-assets#13]
![image](https://user-images.githubusercontent.com/62642184/201588797-473f1dd8-4309-4a4a-a670-9a5dbf32cf55.png)

**Comment by bluwy** [comment]
Can you elaborate the issue here?

**Comment by bluwy** [comment]
This is expected as a variable is dynamic, and the preprocessor doesn't know what import to generate in compile-time.
