### ISSUE TITLE
No "exports" main defined in svelte-parse-markup

### ISSUE THREAD

**Issue by DeepBhat** [bluwy/svelte-preprocess-import-assets#14]
I was trying to use this plugin but I encountered an error.
`error when starting dev server:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in [directory]\node_modules\svelte-parse-markup\package.json`

Here is my config:
`export default defineConfig({
  plugins: [svelte({
    preprocess: [sveltePreprocess({ typescript: true }), importAssets()]
  }
  )],
  optimizeDeps: {
    include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep']
  },
  server: {
    port: 8080
  }
})`

Could you help me with this? I ran `npm install svelte-parse-markup` but that did not solve the issue. Thanks.

**Comment by bluwy** [comment]
Fixed in v0.2.3. It might be that you don't have `"type": "module"` in your `package.json`, but I've fixed that now. It was an unintended breaking change.

**Comment by DeepBhat** [comment]
Thanks a lot!
