### ISSUE TITLE
identical $lib path is only replaced once in a page

### ISSUE THREAD

**Issue by Cayllen** [bluwy/svelte-preprocess-import-assets#20]
Following issue: I have two html tags having a $lib path to an image. The first path is resolved - the second one is not. I don't understand why

![image](https://github.com/bluwy/svelte-preprocess-import-assets/assets/27898791/d46b7a95-2f91-42ce-94f2-d04464d964f0)
![image](https://github.com/bluwy/svelte-preprocess-import-assets/assets/27898791/a269d863-6edc-4adb-a872-ab7765bcc2fa)

**Comment by bluwy** [comment]
Following https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary, you need `<meta name="twitter:image"`, not using `property`

**Comment by Cayllen** [comment]
Crazy that this was the issue. Is there any way to see this somehow in a log/code checker?

**Comment by bluwy** [comment]
I don't think so, otherwise it could bring false positives. But glad that's solved for you.
