### ISSUE TITLE
Asset import not working when using as a variable

### ISSUE THREAD

**Issue by moarpie** [bluwy/svelte-preprocess-import-assets#22]
For example 
`<img src="$lib/assets/test.png" alt="">`
works just fine, but declaring a variable with the exact same value to use does not work. 

`let moo = "$lib/assets/test.png";`
`<img src={moo} alt="">`

Produces the following error:
**Error: Not found: /$lib/assets/test.png**

**Comment by bluwy** [comment]
As the readme has shown, the preprocessor currently does this:

**Convert this:**

```svelte
<h1>Look at this image</h1>
<img src="./assets/cool-image.png" alt="cool image" />
```

**Into this:**

```svelte
<script>
  import ___ASSET___0 from './assets/cool-image.png'
</script>

<h1>Look at this image</h1>
<img src={___ASSET___0} alt="cool image" />
```

And it's not possible to convert to an import if the `src` comes from a variable. You'd need to import the asset yourself to get the URL directly.
