### ISSUE TITLE
srcset: failed to parse `srcset`

### ISSUE THREAD

**Issue by gnuletik** [bluwy/svelte-preprocess-import-assets#8]
e.g.
```html
<img srcset="image.png, image.png@2x 1x" >
```

throws error in Vite
```
Error: failed to load module for ssr: /src/img/image.png,
```

The `srcset` regex seems to include the `,` character in the capture group: https://regex101.com/r/rUtHOq/1

https://github.com/bluwy/svelte-preprocess-import-assets/blob/8be2cdfed2c8ce8065cb7af0cfed998552bd54e1/src/index.ts#L147

Thanks for this library!

**Comment by bluwy** [comment]
Thanks for the report! I've fixed the regex and released 0.1.6.
