### ISSUE TITLE
Does this support Typescript?

### ISSUE THREAD

**Issue by rakataprime** [bluwy/svelte-preprocess-import-assets#9]
I have gotten some unexpected token errors from using this on a typescript sveltekit project that is fixed by using js without typescript annotations.  svelte.config.js preprocess settings: `	preprocess: [preprocess() ,importAssets()],`

**Comment by bluwy** [comment]
It does work but requires special configuration for it. See https://github.com/bluwy/svelte-preprocess-import-assets#using-with-svelte-preprocess
